apiVersion: v1
kind: Service
metadata:
  name: bookinventory-frontend
spec:
  selector:
    app: bookinventory-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
