# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: bookinventory-backend
spec:
  selector:
    app: bookinventory
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 # NodePort for accessing the service externally
  type: NodePort
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: bookinventory-frontend
spec:
  selector:
    app: bookinventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort